# Build stage
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
# Force installing dependencies since yarn is specified as packageManager
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
